layout_spectrum: 0.6762636094354093
typography_spectrum: 0.04406509594991803
color:
  brandStrength: 0.44585775188170373
  lightness: 0.6255637805443257
  saturation: 0.7768269823864102
  rhythmicContrast: 0.32596988044679165
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
name: Kommunikationsschmiede
